name: Deploy WordPress plugin
on:
  push:
    tags:
    - "v*"
  pull_request:
    tags:
    - "v*"
jobs:
  build:
    name: Deploy WordPress plugin    
    runs-on: ubuntu-18.04
    steps:      
      - name: Checkout
        uses: actions/checkout@v2      
      - name: Deploy
        uses: yukihiko-shinoda/action-deploy-wordpress-plugin@v2
        env:
          SVN_REPOSITORY_URL: ${{ secrets.SVN_URL }}
          SVN_USER_NAME: ${{ secrets.SVN_USERNAME }}
          SVN_USER_PASSWORD: ${{ secrets.SVN_PASSWORD }}
